input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["positions"]
    codec => "json"
    consumer_threads => 1
    decorate_events => true
    auto_offset_reset => "earliest"
  }
}

filter {
  if [recorded_at] {
    date {
      match => [ "recorded_at", "ISO8601" ]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "positions-%{+YYYY.MM.dd}"
    data_stream => false
    ilm_enabled => false
    manage_template => false
  }
}
